# Generated by Django 4.1.7 on 2023-06-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Phones', 'Phones'), ('Computers', 'Computers')], max_length=50, null=True),
        ),
    ]
