# Generated by Django 4.2.3 on 2023-07-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_poison_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poison',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='poison',
            name='description',
        ),
    ]
