# Generated by Django 4.2.3 on 2023-07-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_amount_poison_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poison',
            name='category',
            field=models.CharField(blank=True, choices=[('Scorpion Poisons', 'Scorpion Poisons'), ('Sanke Venom', 'Sanke Venom'), ('Plant Toxins', 'Plant Toxins'), ('Animal Toxins', 'Animal Toxins')], max_length=50, null=True),
        ),
    ]
