# Generated by Django 4.2.3 on 2023-07-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_poison_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(default=True, upload_to='photo/%y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poison',
            name='photo',
            field=models.ImageField(default=True, null=True, upload_to='photo/%y/%m/%d'),
        ),
    ]
