# Generated by Django 4.2.5 on 2023-10-30 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_cart_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='username',
            new_name='user',
        ),
    ]
