# Generated by Django 4.2.5 on 2023-11-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_alter_cart_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='username',
        ),
    ]
