# Generated by Django 4.2.5 on 2023-11-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_rename_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='username',
            new_name='user',
        ),
    ]
