# Generated by Django 4.2.5 on 2023-11-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='totalOrderItemPrice',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
