# Generated by Django 4.2.5 on 2023-11-03 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_cartitem_totalorderitemprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='totalOrderItemPrice',
        ),
    ]
